name: issues handling
on: 
    issues: 
        types: opened
jobs:
    issues-info:
        runs-on: ubuntu-latest
        steps:
            - name: Output Event Details
              run: echo "${{toJson(github.event)}}"  
